name: design_system
description: "Design System"
version: 0.0.1
homepage: "https://github.com/Sthaynny/design_system"

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  linkify: ^5.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/svg/flags/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
          weight: 800
    - family: DSIcons
      fonts:
        - asset: assets/fonts/DSIcons.ttf
